# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd3da6214be8e0ec1ebddbec92b13bd1e946b030ae29ef7d14818496e54c3e0932a1eb0cf51b69a87bf01be6b37d1b604beb78461e8126ad25b9db1e1bf19557

test:
  secret_key_base: 7f8ea9043903549b80b0fcf507d0d04409a11b1bd698a8c221e5e7c08b746d2285c19febf94f50db5af09653b9951853b0845dafad45ae59e1347bc618d98907

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
